### ISSUE TITLE
Black svg/png 

### ISSUE THREAD

**Issue by grouser** [Kozea/pygal#183] opened 2015-01-13 12:02 UTC
I am running the basic example of the website on Ubuntu 14.04. I have installed all dependencies as it is mentioned in the website but the svg or png image is always black.  I've had a look at old issues with black images but I couldn't find anything useful for this issue.

**Comment by paradoxxxzero** [comment] 2015-01-13 13:33
Duplicate of #103

**Closed by paradoxxxzero** 2015-01-13 13:33 UTC
