### ISSUE TITLE
Legend not displayed properly in PNG 

### ISSUE THREAD

**Issue by cheluis** [Kozea/pygal#285] opened 2015-12-04 14:24 UTC
Hey, I am trying to create a pie chart but when I render it to png it appears like this
![chart](https://cloud.githubusercontent.com/assets/130223/11591814/dab17000-9a9a-11e5-930d-07e69dc6dc7b.png)

The legend looks messed up. I've installed all dependencies for PNG display. The svg versions looks perfect.

**Comment by liZe** [comment] 2015-12-09 10:02
If you use OSX, this bug is a duplicate of Kozea/CairoSVG#71. You have to update the cairo library to 1.14.4.

**Closed** 2016-08-05 09:52 UTC
